### ISSUE TITLE
RuntimeError: Cannot find callable singing-ssl-mos in hubconf

### ISSUE THREAD

**Issue by hylee-250** [South-Twilight/SingMOS#1]
Hello, I follow the example in README.
But RuntimeError occurred like title.
How can I solve this problem?

Thank you for share your repo.

**Comment by South-Twilight** [comment]
Thanks for pointing out this issue. I will fix it soon.

**Comment by South-Twilight** [comment]
@hylee-250 The README is updated now. You can try it again following new instruction.

**Comment by hylee-250** [comment]
> @hylee-250 The README is updated now. You can try it again following new instruction.

Thank you for updating!
I will use it usefully
