### ISSUE TITLE
How to train the SingMOS prediction model with my own datasets?

### ISSUE THREAD

**Issue by ShawnPi233** [South-Twilight/SingMOS#2]
Excellent works! But I wonder if I can train or finetune the model with my own datasets, instead of using the pretrained model for inference. Thanks for your reply.

**Comment by South-Twilight** [comment]
Thank you for your interest in our work. We train the SingMOS model under a variant version of [mos-finetune-ssl](https://github.com/nii-yamagishilab/mos-finetune-ssl) modified by ourselves and we will release it soon.

**Comment by ShawnPi233** [comment]
Thank you for your reply! I look forward to your future work; it holds great significance for me.
